name: GameCI

on: [push]

jobs:

    build:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: MyProject/Library
          key: Library-MyProject-StandaloneWindows
          restore-keys: |
            Library-MyProject-
            Library-

      - uses: game-ci/unity-builder@3b26780ddfe24a0ee2aebb0a65297ab69fc5bb4c # v4.5.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          # see: https://docs.unity3d.com/ScriptReference/BuildTarget.html
          targetPlatform: StandaloneWindows
          projectPath: MyProject
          buildsPath: MyProject/build

      - run: ls -R
